import type { WorkflowDefinition } from './types.js';

/**
 * Pre-configured static workflow definitions for Hurdler.
 * Orchestrates multi-agent pipelines, automated verification loops, and Git attribution.
 */
export const STATIC_WORKFLOWS: Record<string, WorkflowDefinition> = {
  // 1. End-to-End Feature Development Pipeline
  'feature-development': {
    id: 'feature-development',
    title: 'End-to-End Feature Development Pipeline',
    category: 'feature_development',
    description:
      'Complete software engineering workflow: requirements decomposition, parallel domain logic, API routes, UI components, automatic lint/prettify, auto-debugger healing, and agent Git commit attribution.',
    targetFramework: 'nextjs',
    tags: ['feature', 'end-to-end', 'orchestration', 'git', 'fullstack'],
    defaultPrompts: ['global:kiss', 'global:senior-engineer', 'global:isolation'],
    initialBranch: 'feature/new-feature',
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'decompose-requirements',
        title: 'Decompose Requirements & Architecture Plan',
        description: 'Analyze feature request, plan decoupled modules, and define step contracts.',
        agentId: 'orchestrator',
        executionMode: 'agent',
        prompts: ['global:kiss', 'global:senior-engineer', 'agent:orchestrator'],
        tools: ['file:read', 'file:list'],
        modelTier: 'priority',
        reasoningEffort: 'high',
        dependsOn: [],
      },
      {
        id: 'scaffold-domain-services',
        title: 'Scaffold Business Logic & Domain Services',
        description: 'Implement domain models, state transitions, and business rules in strict isolation.',
        agentId: 'business-logic',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:business-logic', 'system:validations'],
        tools: ['file:read', 'file:write', 'file:edit'],
        modules: ['zod'],
        modelTier: 'priority',
        dependsOn: ['decompose-requirements'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'feat(core): scaffold business logic and domain services',
          authorAgentId: 'business-logic',
        },
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
      },
      {
        id: 'implement-api-routes',
        title: 'Implement API Routes & Server Actions',
        description: 'Build backend API endpoints and Server Actions consuming the domain services.',
        agentId: 'business-logic',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:business-logic', 'system:validations', 'system:security-patches'],
        tools: ['file:read', 'file:write', 'file:edit'],
        modules: ['zod'],
        dependsOn: ['scaffold-domain-services'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'feat(api): implement api endpoints and server actions',
          authorAgentId: 'business-logic',
        },
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
      },
      {
        id: 'build-ui-components',
        title: 'Build Responsive UI Components & Views',
        description: 'Implement frontend UI components, state bindings, and modern layout aesthetics.',
        agentId: 'ui-designer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:ui-designer', 'system:performance'],
        tools: ['file:read', 'file:write', 'file:edit'],
        modules: ['lucide-react', 'tailwind'],
        dependsOn: ['implement-api-routes'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'feat(ui): implement responsive UI components and pages',
          authorAgentId: 'ui-designer',
        },
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
      },
      {
        id: 'auto-lint-and-format',
        title: 'Automated Code Verification & Formatting',
        description: 'Runs ESLint validation and Prettier formatting across all touched files without LLM tokens.',
        executionMode: 'automated',
        dependsOn: ['build-ui-components'],
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
      },
      {
        id: 'security-and-validation-audit',
        title: 'Security & Schema Validation Audit',
        description: 'Audits code for OWASP risks, secret leaks, and sanitization gaps.',
        agentId: 'security-reviewer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:security-patches', 'agent:security-reviewer'],
        tools: ['file:read', 'file:edit'],
        dependsOn: ['auto-lint-and-format'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'refactor(security): apply defensive validation and security hardening',
          authorAgentId: 'security-reviewer',
        },
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 2,
        },
      },
      {
        id: 'final-review-and-pr',
        title: 'Final Review & Pull Request Creation',
        description: 'Reviews changed files, runs git diff summary, and creates PR.',
        agentId: 'orchestrator',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:orchestrator'],
        tools: ['git:status', 'git:diff', 'git:pr'],
        dependsOn: ['security-and-validation-audit'],
      },
    ],
  },

  // 2. Root-Cause Bug Fix & Automated Debugging Workflow
  'bug-fix-and-debug': {
    id: 'bug-fix-and-debug',
    title: 'Diagnostic Bug Fix & Verification',
    category: 'debugging',
    description:
      'Pinpoint bugs using AST/lint diagnostics, apply minimal isolated repair, run automated verification, and commit under debugger identity.',
    targetFramework: 'universal',
    tags: ['debug', 'bugfix', 'repair', 'ast'],
    defaultPrompts: ['global:kiss', 'system:refactor-debug'],
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'diagnose-issue',
        title: 'Diagnose Bug & Inspect AST Outlines',
        description: 'Investigate stack traces, AST structure, and failing conditions.',
        agentId: 'debugger',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:refactor-debug'],
        tools: ['file:read', 'code:lint', 'file:list'],
        dependsOn: [],
      },
      {
        id: 'apply-fix',
        title: 'Apply Minimal Targeted Patch',
        description: 'Modify affected code defensively to resolve the bug with zero regressions.',
        agentId: 'debugger',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:refactor-debug', 'system:validations'],
        tools: ['file:read', 'file:edit'],
        dependsOn: ['diagnose-issue'],
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'fix: resolve bug and apply validated patch',
          authorAgentId: 'debugger',
        },
      },
    ],
  },

  // 3. Security Audit & Hardening Workflow
  'security-hardening': {
    id: 'security-hardening',
    title: 'Security Audit & Defensive Hardening',
    category: 'security_hardening',
    description:
      'Systematic vulnerability audit, input sanitization, strict Zod schema enforcement, and security commit attribution.',
    targetFramework: 'universal',
    tags: ['security', 'audit', 'owasp', 'hardening', 'zod'],
    defaultPrompts: ['global:kiss', 'system:security-patches'],
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'audit-vulnerabilities',
        title: 'Audit Codebase for Vulnerabilities',
        description: 'Scan code for unsanitized inputs, authorization bypasses, and injection risks.',
        agentId: 'security-reviewer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:security-reviewer', 'system:security-patches'],
        tools: ['file:read', 'file:list'],
        dependsOn: [],
      },
      {
        id: 'patch-sanitization-and-schemas',
        title: 'Apply Defensive Schemas & Sanitization',
        description: 'Enforce defensive Zod schemas, sanitize inputs, and prevent data leakage.',
        agentId: 'security-reviewer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:security-patches', 'system:validations'],
        tools: ['file:read', 'file:edit'],
        modules: ['zod'],
        dependsOn: ['audit-vulnerabilities'],
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'sec: apply security hardening and defensive schema validations',
          authorAgentId: 'security-reviewer',
        },
      },
    ],
  },

  // 4. Code Quality Refactoring & Optimization Workflow
  'code-refactoring': {
    id: 'code-refactoring',
    title: 'Code Quality Refactoring & Optimization',
    category: 'refactoring',
    description:
      'Analyze AST outlines for redundancy, extract reusable helper functions, streamline async flows, and verify with ESLint.',
    targetFramework: 'universal',
    tags: ['refactor', 'optimization', 'clean-code', 'ast'],
    defaultPrompts: ['global:kiss', 'system:performance'],
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'analyze-ast-and-complexity',
        title: 'Analyze Code Structure & Symbol Complexity',
        description: 'Inspect AST outlines to identify redundant logic and optimization targets.',
        agentId: 'code-optimizer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:performance'],
        tools: ['file:read', 'file:list'],
        dependsOn: [],
      },
      {
        id: 'refactor-and-deduplicate',
        title: 'Refactor Logic & Extract Shared Helpers',
        description: 'Consolidate duplicate logic into helper functions and optimize performance.',
        agentId: 'code-optimizer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:performance', 'system:refactor-debug'],
        tools: ['file:read', 'file:edit', 'file:write'],
        dependsOn: ['analyze-ast-and-complexity'],
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'refactor: optimize performance and deduplicate helper functions',
          authorAgentId: 'code-optimizer',
        },
      },
    ],
  },

  // 5. Greenfield Next.js App Initialization Workflow
  'greenfield-nextjs-app': {
    id: 'greenfield-nextjs-app',
    title: 'Greenfield Next.js Project Scaffolding',
    category: 'greenfield',
    description:
      'Bootstrap a brand new Next.js project: directory architecture, database schemas, backend services, frontend layouts, and git initialization.',
    targetFramework: 'nextjs',
    tags: ['greenfield', 'nextjs', 'fullstack', 'bootstrap'],
    defaultPrompts: ['global:kiss', 'global:senior-engineer'],
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'scaffold-project-structure',
        title: 'Scaffold Project Architecture & Layout',
        description: 'Create directory layout, package configurations, and base entry points.',
        agentId: 'orchestrator',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:orchestrator'],
        tools: ['file:read', 'file:write', 'file:list'],
        dependsOn: [],
      },
      {
        id: 'scaffold-database-models',
        title: 'Scaffold Database Schemas & Models',
        description: 'Define relational entities, validation schemas, and database client.',
        agentId: 'database-manager',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:database-manager', 'system:validations'],
        tools: ['file:read', 'file:write'],
        modules: ['prisma', 'zod'],
        dependsOn: ['scaffold-project-structure'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'feat(db): scaffold database schemas and relational models',
          authorAgentId: 'database-manager',
        },
      },
      {
        id: 'create-core-services',
        title: 'Implement Core Business Logic Services',
        description: 'Implement domain business logic and backend service handlers.',
        agentId: 'business-logic',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:business-logic', 'system:validations'],
        tools: ['file:read', 'file:write'],
        modules: ['zod'],
        dependsOn: ['scaffold-database-models'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'feat(services): implement core domain business services',
          authorAgentId: 'business-logic',
        },
      },
      {
        id: 'create-frontend-ui',
        title: 'Create Frontend Layout & Views',
        description: 'Create responsive page layouts, design system styles, and interactive components.',
        agentId: 'ui-designer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:ui-designer'],
        tools: ['file:read', 'file:write'],
        modules: ['tailwind', 'lucide-react'],
        dependsOn: ['create-core-services'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'feat(ui): scaffold application layout and views',
          authorAgentId: 'ui-designer',
        },
      },
      {
        id: 'verify-and-format',
        title: 'Automated Lint, Prettify & Verification',
        description: 'Verify code formatting, ESLint rules, and syntax integrity across all files.',
        executionMode: 'automated',
        dependsOn: ['create-frontend-ui'],
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
      },
    ],
  },

  // 6. Fast Single-File Atomic Edit Workflow
  'single-file-edit': {
    id: 'single-file-edit',
    title: 'Atomic Single-File Edit & Verification',
    category: 'atomic_pipeline',
    description:
      'Lightweight workflow designed for smaller LLMs or fast surgical file edits with automated lint verification and git commit.',
    targetFramework: 'universal',
    tags: ['atomic', 'fast', 'single-file', 'lightweight'],
    defaultPrompts: ['global:kiss', 'system:validations'],
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'apply-atomic-edit',
        title: 'Apply Atomic File Modification',
        description: 'Read target file, apply modification, and ensure integrity.',
        agentId: 'business-logic',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:validations'],
        tools: ['file:read', 'file:edit'],
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'fix(atomic): apply file modification and verify formatting',
          authorAgentId: 'business-logic',
        },
        dependsOn: [],
      },
    ],
  },

  // 7. Atomic Capability Multi-Pass Pipeline
  'atomic-capability-pipeline': {
    id: 'atomic-capability-pipeline',
    title: 'Atomic Capability Sequential Pipeline',
    category: 'atomic_pipeline',
    description:
      'Step-by-step pipeline where each pass isolates a single engineering responsibility (Logic -> Validations -> Security -> Format -> Commit).',
    targetFramework: 'universal',
    tags: ['atomic', 'multi-pass', 'capability-isolated'],
    defaultPrompts: ['global:kiss'],
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'logic-pass',
        title: 'Pass 1: Pure Business Logic Scaffolding',
        description: 'Scaffold core functions and interfaces without secondary concerns.',
        agentId: 'business-logic',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:business-logic'],
        tools: ['file:read', 'file:write'],
        dependsOn: [],
      },
      {
        id: 'validation-pass',
        title: 'Pass 2: Defensive Schema & Validation Hardening',
        description: 'Add runtime Zod validations and defensive input checks.',
        agentId: 'business-logic',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:validations'],
        tools: ['file:read', 'file:edit'],
        modules: ['zod'],
        dependsOn: ['logic-pass'],
      },
      {
        id: 'security-pass',
        title: 'Pass 3: Security & Sanitization Review',
        description: 'Inspect for security vulnerabilities and apply sanitization patches.',
        agentId: 'security-reviewer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:security-patches'],
        tools: ['file:read', 'file:edit'],
        dependsOn: ['validation-pass'],
      },
      {
        id: 'format-and-commit-pass',
        title: 'Pass 4: Automated Lint, Format & Commit',
        description: 'Validate ESLint, Prettier, and commit as business logic author.',
        executionMode: 'automated',
        dependsOn: ['security-pass'],
        lintAction: {
          enabled: true,
          fix: true,
          autoDebug: true,
          maxDebugRetries: 3,
        },
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'feat(atomic): completed multi-pass atomic capability pipeline',
          authorAgentId: 'business-logic',
        },
      },
    ],
  },

  // 7. Playwright UI Visual & E2E Verification Pipeline
  'ui-visual-verification': {
    id: 'ui-visual-verification',
    title: 'Playwright UI Visual & E2E Verification Pipeline',
    category: 'custom',
    description:
      'Inspects live frontend UI views with Playwright, captures compressed JPEG screenshots, correlates rendered DOM with source components via Mapper, executes user interactions, and verifies visual/functional integrity.',
    targetFramework: 'nextjs',
    tags: ['playwright', 'ui', 'screenshot', 'e2e', 'visual-regression', 'verification'],
    defaultPrompts: ['global:kiss', 'global:senior-engineer'],
    initialBranch: 'test/ui-visual-verification',
    isBuiltin: true,
    active: true,
    steps: [
      {
        id: 'capture-ui-screens',
        title: 'Capture UI Viewport Screenshots & DOM Snapshot',
        description: 'Navigate to target routes, take compressed JPEG screenshots, and extract rendered DOM structure.',
        agentId: 'tester',
        executionMode: 'agent',
        prompts: ['global:kiss', 'system:playwright-testing'],
        tools: ['playwright_navigate_and_screenshot', 'playwright_inspect_page', 'playwright_capture_ui_context'],
        modules: ['playwright'],
        modelTier: 'standard',
        dependsOn: [],
      },
      {
        id: 'visual-design-audit',
        title: 'Visual Design & Layout Inspection',
        description: 'Analyze captured JPEG visuals and DOM structure to evaluate design tokens, responsive spacing, and typography.',
        agentId: 'ui-designer',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:ui-designer', 'system:ui-visual-inspection'],
        tools: ['file:read', 'file:edit', 'playwright_capture_ui_context'],
        modules: ['lucide-react', 'tailwind', 'playwright'],
        modelTier: 'priority',
        reasoningEffort: 'high',
        dependsOn: ['capture-ui-screens'],
      },
      {
        id: 'execute-e2e-user-flows',
        title: 'Execute E2E Browser Test Suite',
        description: 'Run interactive Playwright action sequences (clicks, form fills, assertions) to verify end-to-end user workflows.',
        agentId: 'tester',
        executionMode: 'agent',
        prompts: ['global:kiss', 'agent:tester', 'system:playwright-testing'],
        tools: ['playwright_run_actions', 'playwright_run_test_suite', 'file:read', 'file:write'],
        modules: ['playwright'],
        modelTier: 'standard',
        dependsOn: ['visual-design-audit'],
        gitAction: {
          stage: true,
          commit: true,
          commitMessage: 'test(e2e): add and verify playwright browser test suite',
          authorAgentId: 'tester',
        },
      },
    ],
  },
};
